=begin
#Constant Contact API v3

#Swagger build version 3.0.2475

The version of the OpenAPI document: 1.0.87
Contact: webservices@constantcontact.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'date'
require 'time'

module ConstantContactClient
  class GetContactTrackingCountReport200ResponseCampaignActivitiesInner
    # The unique id of the activity for an e-mail campaign.
    attr_accessor :campaign_activity_id

    # The last date at which the email was sent to this contact.
    attr_accessor :start_on

    # The number of times the email has bounced for this contact.
    attr_accessor :em_bounces

    # The number of times this contact has clicked a link in this email.
    attr_accessor :em_clicks

    # The number of times this contact has forwarded this email.
    attr_accessor :em_forwards

    # The number of times this contact has opened this email.
    attr_accessor :em_opens

    # The number of times the email was sent to this contact.
    attr_accessor :em_sends

    # The number of times this contact has opted out.
    attr_accessor :em_unsubscribes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'campaign_activity_id' => :'campaign_activity_id',
        :'start_on' => :'start_on',
        :'em_bounces' => :'em_bounces',
        :'em_clicks' => :'em_clicks',
        :'em_forwards' => :'em_forwards',
        :'em_opens' => :'em_opens',
        :'em_sends' => :'em_sends',
        :'em_unsubscribes' => :'em_unsubscribes'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'campaign_activity_id' => :'String',
        :'start_on' => :'Time',
        :'em_bounces' => :'Integer',
        :'em_clicks' => :'Integer',
        :'em_forwards' => :'Integer',
        :'em_opens' => :'Integer',
        :'em_sends' => :'Integer',
        :'em_unsubscribes' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConstantContactClient::GetContactTrackingCountReport200ResponseCampaignActivitiesInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConstantContactClient::GetContactTrackingCountReport200ResponseCampaignActivitiesInner`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'campaign_activity_id')
        self.campaign_activity_id = attributes[:'campaign_activity_id']
      else
        self.campaign_activity_id = nil
      end

      if attributes.key?(:'start_on')
        self.start_on = attributes[:'start_on']
      else
        self.start_on = nil
      end

      if attributes.key?(:'em_bounces')
        self.em_bounces = attributes[:'em_bounces']
      else
        self.em_bounces = nil
      end

      if attributes.key?(:'em_clicks')
        self.em_clicks = attributes[:'em_clicks']
      else
        self.em_clicks = nil
      end

      if attributes.key?(:'em_forwards')
        self.em_forwards = attributes[:'em_forwards']
      else
        self.em_forwards = nil
      end

      if attributes.key?(:'em_opens')
        self.em_opens = attributes[:'em_opens']
      else
        self.em_opens = nil
      end

      if attributes.key?(:'em_sends')
        self.em_sends = attributes[:'em_sends']
      else
        self.em_sends = nil
      end

      if attributes.key?(:'em_unsubscribes')
        self.em_unsubscribes = attributes[:'em_unsubscribes']
      else
        self.em_unsubscribes = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @campaign_activity_id.nil?
        invalid_properties.push('invalid value for "campaign_activity_id", campaign_activity_id cannot be nil.')
      end

      if @start_on.nil?
        invalid_properties.push('invalid value for "start_on", start_on cannot be nil.')
      end

      if @em_bounces.nil?
        invalid_properties.push('invalid value for "em_bounces", em_bounces cannot be nil.')
      end

      if @em_clicks.nil?
        invalid_properties.push('invalid value for "em_clicks", em_clicks cannot be nil.')
      end

      if @em_forwards.nil?
        invalid_properties.push('invalid value for "em_forwards", em_forwards cannot be nil.')
      end

      if @em_opens.nil?
        invalid_properties.push('invalid value for "em_opens", em_opens cannot be nil.')
      end

      if @em_sends.nil?
        invalid_properties.push('invalid value for "em_sends", em_sends cannot be nil.')
      end

      if @em_unsubscribes.nil?
        invalid_properties.push('invalid value for "em_unsubscribes", em_unsubscribes cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @campaign_activity_id.nil?
      return false if @start_on.nil?
      return false if @em_bounces.nil?
      return false if @em_clicks.nil?
      return false if @em_forwards.nil?
      return false if @em_opens.nil?
      return false if @em_sends.nil?
      return false if @em_unsubscribes.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          campaign_activity_id == o.campaign_activity_id &&
          start_on == o.start_on &&
          em_bounces == o.em_bounces &&
          em_clicks == o.em_clicks &&
          em_forwards == o.em_forwards &&
          em_opens == o.em_opens &&
          em_sends == o.em_sends &&
          em_unsubscribes == o.em_unsubscribes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [campaign_activity_id, start_on, em_bounces, em_clicks, em_forwards, em_opens, em_sends, em_unsubscribes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = ConstantContactClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
