# -*- encoding: utf-8 -*-

=begin
#Constant Contact API v3

#Swagger build version 3.0.2475

The version of the OpenAPI document: 1.0.106
Contact: webservices@constantcontact.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "constant_contact_client/version"

Gem::Specification.new do |s|
  s.name        = "constant_contact_client"
  s.version     = ConstantContactClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Constant Contact"]
  s.email       = ["ctct-publicapi@constantcontact.com"]
  s.homepage    = "https://v3.developer.constantcontact.com/"
  s.summary     = "Constant Contact API v3 Ruby Gem"
  s.description = "Swagger build version 3.0.2475"
  s.license     = "BSD 3-Clause"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
