name: Ruby Release

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    strategy:
      matrix:
        ruby-version: [ "2.7", "3.0", "3.1" ]
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - run: bundle install
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create tag from commit
        uses: christophebedard/tag-version-commit@v1
        id: tag_version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version_regex: '([0-9]+\.[0-9]+\.[0-9]+)'
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.tag }}
          name: Release ${{ steps.tag_version.outputs.tag }}
    - name: Publish
      uses: rubygems/release-gem@v1
